# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  nifi_workshop_mongo:

services:
  mongo-express:
    # https://hub.docker.com/_/mongo-express/tags
    image: mongo-express:0.54
    container_name: 'mongo-express'
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
    links:
      - mongo
    networks:
      - "nifi-wkshop"
  mongo:
    # https://hub.docker.com/_/mongo/tags
    image: mongo:4.2.6
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    ports:
      - "27017:27017"
    volumes:
      - nifi_workshop_mongo:/data/db
    networks:
      - "nifi-wkshop"
  mongodb-exporter:
    # https://hub.docker.com/r/bitnami/mongodb-exporter/tags/
    image: bitnami/mongodb-exporter:0.11.0
    container_name: 'mongo-exporter'
    networks:
      - "nifi-wkshop"
    ports:
      - 9216:9216
    environment:
      MONGODB_URI: 'mongodb://mongo:27017'