# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  nifi_workshop_nifi_state:
  nifi_workshop_nifi_db:
  nifi_workshop_nifi_flowfile:
  nifi_workshop_nifi_content:
  nifi_workshop_nifi_pr:
  nifi_workshop_nifi_data:
  nifi_workshop_nifi_conf:
  nifi_workshop_nifi_logs:
  nifi_workshop_nifi_state_2:
  nifi_workshop_nifi_db_2:
  nifi_workshop_nifi_flowfile_2:
  nifi_workshop_nifi_content_2:
  nifi_workshop_nifi_pr_2:
  nifi_workshop_nifi_data_2:
  nifi_workshop_nifi_conf_2:
  nifi_workshop_nifi_logs_2:

services:
  nifi:
#    build:
#      context: ./nifi
#      dockerfile: Dockerfile
    image: apache/nifi:1.12.0
    container_name: "nifi"
    networks:
      - "nifi-wkshop"
    ports:
      - "8080:8080"
      - "9092:9092"
    environment:
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./conf/db.properties
      - NIFI_REMOTE_INPUT_HOST=nifi
      - NIFI_REMOTE_INPUT_SOCKET_PORT=8000
    volumes:
      - nifi_workshop_nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_workshop_nifi_data:/opt/nifi/nifi-current/data
      - nifi_workshop_nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_workshop_nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_workshop_nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_workshop_nifi_state:/opt/nifi/nifi-current/state
      - nifi_workshop_nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_workshop_nifi_pr:/opt/nifi/nifi-current/provenance_repository
      - ./postgres/postgresql-42.2.14.jar:/opt/nifi/nifi-current/lib/postgresql-42.2.14.jar
      - ./postgres/db.properties:/opt/nifi/nifi-current/conf/db.properties
      - ./nifi/libs/nifi-metrics-1.12.0.jar:/opt/nifi/nifi-current/lib/nifi-metrics-1.12.0.jar
      - ./nifi/libs/metrics-jvm-4.1.2.jar:/opt/nifi/nifi-current/lib/metrics-jvm-4.1.2.jar
      - ./nifi/libs/metrics-core-4.1.2.jar:/opt/nifi/nifi-current/lib/metrics-core-4.1.2.jar
      - ./nifi/libs/http-builder-0.7.1.jar:/opt/nifi/nifi-current/lib/http-builder-0.7.1.jar
      - ./nifi/libs/nifi-custom-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-custom-nar-1.0.nar
      - ./nifi/libs/nifi-customservice-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-customservice-nar-1.0.nar
      - ./nifi/libs/nifi-customservice-api-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-customservice-api-nar-1.0.nar
  nifitwo:
#    build:
#      context: ./nifi
#      dockerfile: Dockerfile
    image: apache/nifi:1.12.0
    container_name: "nifitwo"
    networks:
      - "nifi-wkshop"
    ports:
      - "8089:8080"
      - "9099:9092"
    environment:
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./conf/db.properties
      - NIFI_REMOTE_INPUT_HOST=nifitwo
      - NIFI_REMOTE_INPUT_SOCKET_PORT=8001
    volumes:
      - nifi_workshop_nifi_db_2:/opt/nifi/nifi-current/database_repository
      - nifi_workshop_nifi_data_2:/opt/nifi/nifi-current/data
      - nifi_workshop_nifi_conf_2:/opt/nifi/nifi-current/conf
      - nifi_workshop_nifi_logs_2:/opt/nifi/nifi-current/logs
      - nifi_workshop_nifi_flowfile_2:/opt/nifi/nifi-current/flowfile_repository
      - nifi_workshop_nifi_state_2:/opt/nifi/nifi-current/state
      - nifi_workshop_nifi_content_2:/opt/nifi/nifi-current/content_repository
      - nifi_workshop_nifi_pr_2:/opt/nifi/nifi-current/provenance_repository
      - ./postgres/postgresql-42.2.14.jar:/opt/nifi/nifi-current/lib/postgresql-42.2.14.jar
      - ./postgres/db.properties:/opt/nifi/nifi-current/conf/db.properties
      - ./nifi/libs/nifi-metrics-1.12.0.jar:/opt/nifi/nifi-current/lib/nifi-metrics-1.12.0.jar
      - ./nifi/libs/metrics-jvm-4.1.2.jar:/opt/nifi/nifi-current/lib/metrics-jvm-4.1.2.jar
      - ./nifi/libs/metrics-core-4.1.2.jar:/opt/nifi/nifi-current/lib/metrics-core-4.1.2.jar
      - ./nifi/libs/http-builder-0.7.1.jar:/opt/nifi/nifi-current/lib/http-builder-0.7.1.jar
      - ./nifi/libs/nifi-custom-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-custom-nar-1.0.nar
      - ./nifi/libs/nifi-customservice-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-customservice-nar-1.0.nar
      - ./nifi/libs/nifi-customservice-api-nar-1.0.nar:/opt/nifi/nifi-current/lib/nifi-customservice-api-nar-1.0.nar
  splunkforwarder-nifi1:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder-nifi1
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_ADD=monitor /opt/nifi/nifi-current/logs
      - SPLUNK_PASSWORD=password
    restart: always
    volumes:
      - nifi_workshop_nifi_logs:/opt/nifi/nifi-current/logs
  splunkforwarder-nifi2:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder-nifi2
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_ADD=monitor /opt/nifi/nifi-current/logs
      - SPLUNK_PASSWORD=password
    restart: always
    volumes:
      - nifi_workshop_nifi_logs_2:/opt/nifi/nifi-current/logs