# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  nifi_workshop_nifi_state:
  nifi_workshop_nifi_db:
  nifi_workshop_nifi_flowfile:
  nifi_workshop_nifi_content:
  nifi_workshop_nifi_pr:
  nifi_workshop_nifi_data:
  nifi_workshop_nifi_conf:
  nifi_workshop_nifi_logs:

services:
  nifi:
    # https://hub.docker.com/r/apache/nifi/tags
    image: apache/nifi:1.11.4
    networks:
      - "nifi-wkshop"
    ports:
      - "8080"
      - "9092"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTP_HOST=0.0.0.0
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./conf/db.properties
    volumes:
      - nifi_workshop_nifi_db:/opt/nifi/nifi-current/database_repository
      - nifi_workshop_nifi_data:/opt/nifi/nifi-current/data
      - nifi_workshop_nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_workshop_nifi_logs:/opt/nifi/nifi-current/logs
      - nifi_workshop_nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_workshop_nifi_state:/opt/nifi/nifi-current/state
      - nifi_workshop_nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_workshop_nifi_pr:/opt/nifi/nifi-current/provenance_repository
      - ./postgres/postgresql-42.2.14.jar:/opt/nifi/nifi-current/lib/postgresql-42.2.14.jar
      - ./postgres/db.properties:/opt/nifi/nifi-current/conf/db.properties