# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

services:
  nifi:
    # https://hub.docker.com/r/apache/nifi
    image: apache/nifi:1.12.0
    networks:
      - "nifi-wkshop"
    ports:
      - "8080"
      - "9092"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181 #This env var by default already change the state-management.xml and the nifi.zookeeper.connect.string prop
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_ELECTION_MAX_CANDIDATES=2
      - NIFI_VARIABLE_REGISTRY_PROPERTIES=./conf/db.properties