# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

volumes:
  log_volume_splunk:

services:
  zookeeper:
    # https://hub.docker.com/r/bitnami/zookeeper/tags
    image: bitnami/zookeeper:3.6.1
    networks:
      - "nifi-wkshop"
    hostname: zookeeper
    ports:
      - "8084:8084"
    container_name: 'zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_ENABLE_PROMETHEUS_METRICS=true
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=8084
  nginx:
    container_name: nginx
    image: nginx:1.17
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:8080"
      - "9092:9092"
    networks:
      - "nifi-wkshop"
  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder-cluster
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_USER=root
      - SPLUNK_ADD=monitor /opt/nifi/nifi-current/logs
      - SPLUNK_PASSWORD=password
    restart: always
    volumes:
      - log_volume_splunk:/opt/nifi/nifi-current/logs