# https://docs.docker.com/compose/compose-file/
version: "3.6"

# https://docs.docker.com/compose/compose-file/#networks
networks:
  nifi-wkshop:

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: 'postgres:12'
    command: postgres -c 'max_connections=500'
    networks:
      - "nifi-wkshop"
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
      - './postgres/init/:/docker-entrypoint-initdb.d/'
    environment:
      - POSTGRES_USER=nifi
      - POSTGRES_PASSWORD=nifi
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=nifi